### ISSUE TITLE
Project suggestions

### ISSUE THREAD

**Issue by Soldier233** [jiongjionger/NeverLag#1]
I am so lucky that I will post the first issue in your project.
And I have some ideas about it.I found that you didn't do something to prevent the player copying items through nether portal.
I hope you can add a bug fixer about the nether portal.
As you know,the nether portals often become the cause of some item-copying bug,And player will also be trapped in it if someone else place blocks besides the portals.
I hope you can add the function soon.

希望dalao能看的懂我的垃圾英文

**Comment by xjboss** [comment]
You know your English very "垃圾" why don't using Chinese.

**Comment by jiongjionger** [comment]
非常感谢你能在插件尚未完工的状态就发现和提供建议。但是我并不明白你的意思，请问这个刷物品的bug具体在什么版本的服务端下出现，具体的复现步骤是怎样的？放置什么方块在地狱门附近会有这个问题？

**Comment by Soldier233** [comment]
这个是在我空岛服内一些玩家刷物品后调查发现的，不知道是原版的BUG还是AskyBlock的BUG，不过既然作为一个高度集成的BUG修复，服务器优化插件，就算是ASkyBlock的问题最好也要做一下拦截
如果一个玩家在地狱门前任意扔一个物品，并迅速通过命令传送到目标地狱门的地狱出口位置，再迅速用命令传送回来，会发现不仅在地狱里捡了一个物品，并且主世界的物品也还在，从而刷取物品
另外，卡地狱门的问题我觉得也可以集成一下

For my "垃圾"

**Comment by jiongjionger** [comment]
你描述的刷物品步骤已经可以防御。
具体请看：
https://github.com/jiongjionger/NeverLag/blob/master/cn/jiongjionger/neverlag/controler/ThroughPortalDisabler.java
