### ISSUE TITLE
建议：插件的一些Bug或者说改进

### ISSUE THREAD

**Issue by Vlvxingze** [jiongjionger/NeverLag#16]
乐乐我，，，诺，我是真心来提建议的，
嗯。

1.BlockExplodeEvent在1.8才出现，老版本一旦有这个监听器会在开启时报错。
2.插件如果已经有了反负数物品，那么就无需防御玩家破坏正在打开的箱子，可能会浪费资源。
3.我记得刷怪笼类型好像也可以用发射器修改刷怪类型，这条不确定，如果错了求原谅。

**Comment by jiongjionger** [comment]
1. 感谢提醒
2. 破坏正在浏览的箱子和负数物品无关，主要是虚体卡成实体
3. 发射器发射怪物蛋是直接生成这个怪物，无法改变刷怪笼
