### ISSUE TITLE
怪物清理相关

### ISSUE THREAD

**Issue by PlaYeRpgitem** [jiongjionger/NeverLag#18]
在服务端未添加插件时
怪物根据难度正常生成
但是添加插件后因怪物数量限制功能导致怪物及时在困难模式下也不会正常刷出
即使关闭怪物生成限制这个功能
以上问题出现在1.3.0版本
且1.10以后的协议库对插件一些事件报错
望重视

**Comment by jiongjionger** [comment]
目前开源的是NeverLag2.0，几乎是代码重构的版本。在插件正式更新发布以后，如果还存在这个问题，请reopen这个issues。非常感谢：）
