### ISSUE TITLE
Bug或者建议？不要在低TPS时gc内存。

### ISSUE THREAD

**Issue by Vlvxingze** [jiongjionger/NeverLag#20]
嗯，我刚才看到了一个类：LowTpsAction，
看起来是在服务器tps低的时候执行。
但是我非常不建议在低TPS时进行gc。
亲测每次gc都会导致服务器短暂接近一秒的卡顿。
人多时可能更长。
如果在低TPS时进行gc，绝对是火上浇油。

所以吧，Gc功能我建议应该定期执行，当服务器卡顿反而不应该执行了。

至于释放内存，应该弄区块卸载比较好吧。

**Comment by jiongjionger** [comment]
这个功能是有开关的且默认关闭
