### ISSUE TITLE
PaperSpigot1.8.8使用NeverLag1.3.0出错

### ISSUE THREAD

**Issue by TTTornado** [jiongjionger/NeverLag#24]
PaperSpigot1.8.8使用NeverLag1.3.0出现Default system encoding may have misread config.yml
两种编码的插件都试过了，手动转码也试过了，不行
看到插件还在施工，就直接来Issue了=w=
望大佬测试一下
话说有没有啥同类插件啊，先救个急

**Comment by shaokeyibb** [comment]
（Jiongjionger原谅我）VLagger可以

**Comment by TTTornado** [comment]
噢噢好的

2017年8月2日 11:10，"shaokeyibb" <notifications@github.com>写道：

**Comment by andylizi** [comment]
NeverLag 2.0 的配置文件系统与之前不同，在任何操作系统上都是 UTF-8 编码。

**Comment by TTTornado** [comment]
OK，不过最近上学用不了电脑，等放假了试一下。
说起来没看到2.0版的下载链接？或者是因为我没怎么用过GitHub所以找不到么...

2017年11月14日 14:05，"andylizi" <notifications@github.com>写道：

NeverLag 2.0 的配置文件系统与之前不同，在任何操作系统上都是 UTF-8 编码。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jiongjionger/NeverLag/issues/24#issuecomment-344155803>,
or mute the thread

**Comment by andylizi** [comment]
https://github.com/jiongjionger/NeverLag/issues/30#issuecomment-321237158

**Comment by TTTornado** [comment]
好的，谢谢梨子=w=

2017年11月17日 21:19，"andylizi" <notifications@github.com>写道：
