### ISSUE TITLE
能否增加死亡自动重生功能？

### ISSUE THREAD

**Issue by shaokeyibb** [jiongjionger/NeverLag#29]
如题

**Comment by andylizi** [comment]
emmmm.....既然这个插件的定位是

> 专注于优化我的世界服务端性能、减少延迟、修复服务端/其他常用插件BUG、限制或禁用破坏多人游戏平衡的游戏机制的插件

加这个功能好像不太合适

**Comment by jiongjionger** [comment]
死亡自动重生并不能减少服务端卡顿。这应该由其他插件来实现这个功能：）
