### ISSUE TITLE
建议：添加全息掉落物清理警告

### ISSUE THREAD

**Issue by SotrForgotten** [jiongjionger/NeverLag#3]
在掉落物清理前几(十)秒，在掉落物上方以"浮空字"形式显示倒计时

**Comment by jiongjionger** [comment]
非常感谢你的建议，我会尽快实现这个功能:)

**Comment by jiongjionger** [comment]
非常抱歉，为了兼容1.6.4~1.7.10的服务端，实现全息的倒数计时过于损伤性能，我不得不放弃实现这个功能。（以1.7.2为例，1.7.2的Item和Entity均没有setCustomName和setCustomName方法，要实现这样的功能只能使用Hologram的方式发包，且需要在清理后发送用于全息显示的实体移除的数据包，过于消耗性能）

如果你有更好的实现方式，欢迎提出：）

**Comment by jiongjionger** [comment]
你建议的功能已经实现，感谢：）
