### ISSUE TITLE
在1.12  java8环境下启动配置无限还原的问题

### ISSUE THREAD

**Issue by storm-wang** [jiongjionger/NeverLag#35]
我编译最新版本后  修改配置文件启动 结果配置文件被还原,无论如何都无法启用.
并非编码问题与其他系列为,调试后发现应该是插件本身配置文件问题. 

cn.jiongjionger.neverlag.config.ConfigManager.java中
noClearItemWorld
noClearItemId
noClearEntityWorld ...等等HashMap都没有初值,都是null

运行到cn.jiongjionger.neverlag.config.AbstractConfig.java  第 86~88行
				Object def = f.get(this);
				if (!config.contains(key)) {
					config.addDefault(key, def);
					return;
				}
当不存在节点时增加的default值...但增加的值也是null  null值节点在保存的时候被忽略,然后直接return了,所以每次到这就不往下读配置  写出一遍初始配置,然后又启动又到这里重复一遍  配置怎么都读不了....

我表达的不是很清楚,望修复此问题...

**Comment by jiongjionger** [comment]
目前开源的是NeverLag2.0，插件还处于开发未完工的状态（WIP），尚不可用。

**Comment by andylizi** [comment]
已修复，感谢反馈。
