### ISSUE TITLE
建议:添加服务器无人时自动休眠等问题

### ISSUE THREAD

**Issue by shaokeyibb** [jiongjionger/NeverLag#38]
1.当服务器没有玩家时自动休眠服务器，减少内存占用    
2.如果上面的不行的话那么能不能在没玩家的时候不要再进行掉落物清理了?这个在后台上面显示真的很坑。。。。    
3.能不能进行动态内存调节，群组服表示这玩意会很有用

**Comment by sjx233** [comment]
gc卡服，native不稳定
~~有谁看成naive么~~

**Comment by andylizi** [comment]
动态内存调节指的是什么？如果是运行时修改 `-Xmx` 和 `-Xms` 指定的值的话，不可能。

如果自动休眠服务器指的是在主线程 sleep 的话，一个是并不能减少内存占用，一个是实现起来会有很多问题（spigot 的 WatchDog、影响  BukkitScheduler 、影响其他插件等）。虽然这些并不是不能解决，但感觉这个功能没多大用啊…无非就是节省 CPU 而已，但节省了又能怎么样，，又不能攒下来留着以后用对吧（摊手

掉落物清理提示感觉可以改为如果清理数量为 0 就不显示。

不代表 NeverLag 作者的观点。

**Comment by jiongjionger** [comment]
1. 没有玩家的时候自动休眠，除非关服，否则无法减少内存的占用。但是可以通过sleep主线程来减少CPU占用，但是当服务端没有玩家的时候占用本来就极低，sleep主线程并没有太大的必要，还可能导致很多不可预知的问题，因为Schedule是在主线程被分配的，这可能导致一些插件的定时保存功能产生偏差甚至失效，更为极端的情况是占用大量IO导致吃完单个逻辑CPU的算力。

2. 扫地大妈物品清理为0时不显示是一个不错的建议：）

3. 动态内存调整，请问具体是指？

**Comment by shaokeyibb** [comment]
嗯嗯，知道了，动态内存调整那个暂时算了吧我再想想【是没有理解Java的内存回收机制胡说的】
