### ISSUE TITLE
新的BUG汇报：某机制可使玩家无视木牌锁箱

### ISSUE THREAD

**Issue by shaokeyibb** [jiongjionger/NeverLag#40]
没错又是我shaokeyibb
今天发现了一个问题，我不知道他是mc的bug还是neverlag的锅还是NPC的问题，所以我在这里告诉你们：当玩家离开箱子或是其他东西的时候，这些东西会自动变成石头（貌似是为了节约CPU占用？），如果在服务器网络卡顿（或TPS较低）时，玩家可快速跑到那个石头旁然后当石头变成箱子的时候右键！然后箱子就被打开了！

**Comment by LinEvil** [comment]
Neverlag并不会导致您的容器单位变成石头方块，建议排查其他插件以进一步确认原因。
我个人认为您的问题可能与假矿或者与带有相似的方块混淆功能的插件有关。
此外，如果能，请详细描述问题的重现步骤并具体说明您使用的插件情况。

**Comment by andylizi** [comment]
这是假矿插件的效果（或是spigot自带的假矿功能）。
理论上来说，正常的假矿实现是不可能允许玩家绕过箱子锁的，因为变成石头只是在玩家看起来是石头，服务器仍然认为这是一个箱子（不然你右键也不可能打开）。

建议在反馈bug前先测试bug是否真的存在，而不是猜测bug应该会存在。
