### ISSUE TITLE
疑似问题？

### ISSUE THREAD

**Issue by shaokeyibb** [jiongjionger/NeverLag#43]
NeverLag清理掉落物品时貌似会连着Quickshop的悬浮物品一块清理掉。。。。希望修复

**Comment by andylizi** [comment]
清理后应该能刷回来吧？

**Comment by shaokeyibb** [comment]
可是实际上不行，我用的quickshop是yum重制版的，服务器版本1.10.2

**Comment by jiongjionger** [comment]
新版的快捷商店悬浮物是通过发包实现的，服务器并不存在对应的掉落物实体，不可能被清理的。
如果你使用的是旧版，建议关闭悬浮物展示功能（可以利用水流和漏斗无限刷悬浮物）。
