### ISSUE TITLE
能把1.3.0版本的源码添加到一个分支里吗？

### ISSUE THREAD

**Issue by Himmelt** [jiongjionger/NeverLag#45]
你好，请问现在的代码仓库里有哪个commit是1.3.0版的最后更改吗？没有的话，能否把1.3.0的源码创建到一个新的分支，
1.3.0里有个Bug，没有源码的话改起来有点费劲。

**Comment by endymx** [comment]
现在的版本后台会报错，一刷一大堆，很烦。。

**Comment by andylizi** [comment]
据我所知，NeverLag 2.0 的代码并不基于 1.3.0，而是一个完全重写过的版本，因此提交历史里不包括 1.3.0 版的代码。1.3.0 的源码只有作者 @jiongjionger 才拥有。
