### ISSUE TITLE
建议：集成针对用户名大小写的修复

### ISSUE THREAD

**Issue by SotrForgotten** [jiongjionger/NeverLag#5]
建议添加一个可选修复项，在玩家加入服务器时检测是否存在同名不同大小写的已登录（或已存在）玩家，并做出相关反映（例如提示使用正确大小写）

**Comment by LinEvil** [comment]
authme 中已有相关选项，个人认为没有必要添加此功能。

**Comment by jiongjionger** [comment]
非常感谢你的建议，我会尽快实现这个功能:)

**Comment by jiongjionger** [comment]
你提交的建议已经实现：）
