### ISSUE TITLE
默认配置文件的一处错误

### ISSUE THREAD

**Issue by myunco** [jiongjionger/NeverLag#8]
NeverLag1.3.0_ANSI.jar

默认生成的配置文件NeverLag\config.yml  在第74行 为：  Boat: fasle  
前后文：  
#是否清理船
  Boat: fasle
  #是否清理经验球
  ExpBall: true

这应该是不小心打错了 ，应为为false  而不是fasle

**Comment by andylizi** [comment]
此项目好像是NeverLag的2.0重写版了，应该不会沿用原来的配置文件吧？

**Comment by jiongjionger** [comment]
目前的版本是2.0，代码重头重新写的版本。也新增了大量的可配置项和功能。所以不会沿用老的配置文件。
